services:
  api:
    container_name: "permission-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8080"
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db

  db:
    container_name: "permission-db"
    image: postgres:12
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "permission-db"
      JAVA_OPTS: -javaagent:/usr/local/newrelic-java/newrelic/newrelic.jar
    volumes:
      - permission-db:/var/lib/postgresql/data

volumes:
  permission-db: