version: "3.8"
services:
  api:
    container_name: "permission-api"
    build:
      context: .
    ports:
      - "${API_PORT}:8080"
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db

  db:
    container_name: "permission-db"
    image: postgres:12
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - permission-db:/var/lib/postgresql/data

volumes:
  permission-db: