services:
  api:
    container_name: "permission-api"
    build:
      context: .
    ports:
      - "8082:8080"
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: permission-db
      DB_PORT: 5432
    depends_on:
      - db

  db:
    container_name: "permission-db"
    image: postgres:12
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - permission-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5

volumes:
  permission-db: